apiVersion: apps/v1
kind: Deployment
metadata:
  name: musiccollection-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musiccollectionnginx
  template:
    metadata:
      labels:
        app: musiccollectionnginx
    spec:
      containers:
        - name: nginx
          image: nginx:mainline
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: musiccollection-nginx-volume
      volumes:
        - hostPath:
            path: /run/desktop/mnt/host/{{PROJECT_PATH}}
          name: musiccollection-nginx-volume
---
apiVersion: v1
kind: Service
metadata:
  name: musiccollection-nginx-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: musiccollectionnginx
  ports:
    - name: musiccollectionnginx
      protocol: TCP
      port: 80
      targetPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  name: musiccollection-nodeport
spec:
  type: NodePort
  selector:
    app: musiccollectionnginx
  ports:
    - name: musiccollectionnginx
      protocol: TCP
      port: 4567
      targetPort: 4567
      nodePort: 30100